name: recodiv
channels:
  - defaults
  - conda-forge
dependencies:
  - autopep8=1.6.0
  - lenskit=0.13.1
  - matplotlib=3.5.0
  - numba=0.54.1
  - numpy=1.20.3
  - pandas=1.3.4
  - pip=21.2.4
  - plotly=5.1.0
  - python=3.9.7
  - scikit-learn=1.0.1
  - scipy=1.7.1
  - setuptools=58.0.4
  - tqdm=4.62.3
  - tikzplotlib=0.9.16
  - pip:
    - click==8.0.3
    - dash==2.0.0
    - luigi==3.0.3