name: recodiv
channels:
  - defaults
  - conda-forge
  - plotly
dependencies:
  - matplotlib=3.3.2
  - matplotlib-base=3.3.2
  - numba=0.51.2
  - numpy=1.19.2
  - pandas=1.1.3
  - pip=20.3.1
  - python=3.8.5
  - scipy=1.5.2
  - setuptools=51.0.0
  - tqdm=4.54.1
  - plotly=5.4.0
  - autopep8==1.6.0
  - tikzplotlib==0.9.16
  - scikit-learn=1.0.1
  - lenskit=0.13.1
  - pip:
    - luigi==3.0.2
    - click==8.0.3
    - dash==2.0.0